// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdE3UtFNa5hTNzShwPw9KlCKMrA0CU5SI',
    appId: '1:1023993471021:web:2e6595361913dac8c2d8a4',
    messagingSenderId: '1023993471021',
    projectId: 'tickgo-app',
    authDomain: 'tickgo-app.firebaseapp.com',
    storageBucket: 'tickgo-app.firebasestorage.app',
    measurementId: 'G-49YQDKQXSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbiaWCDdW_oKqnUs5s0HkbrNU6gzFbr8E',
    appId: '1:1023993471021:android:769f4a446a9e2746c2d8a4',
    messagingSenderId: '1023993471021',
    projectId: 'tickgo-app',
    storageBucket: 'tickgo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnr-sS9LB6oNR1ubbwXrfTl6ONkw2YjU0',
    appId: '1:1023993471021:ios:a8e24eeca9006754c2d8a4',
    messagingSenderId: '1023993471021',
    projectId: 'tickgo-app',
    storageBucket: 'tickgo-app.firebasestorage.app',
    iosClientId: '1023993471021-6i9026u8mdsuk80gjfsl48575dlptccm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickgoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnr-sS9LB6oNR1ubbwXrfTl6ONkw2YjU0',
    appId: '1:1023993471021:ios:a8e24eeca9006754c2d8a4',
    messagingSenderId: '1023993471021',
    projectId: 'tickgo-app',
    storageBucket: 'tickgo-app.firebasestorage.app',
    iosClientId: '1023993471021-6i9026u8mdsuk80gjfsl48575dlptccm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickgoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdE3UtFNa5hTNzShwPw9KlCKMrA0CU5SI',
    appId: '1:1023993471021:web:e48b0ba512d0f6d6c2d8a4',
    messagingSenderId: '1023993471021',
    projectId: 'tickgo-app',
    authDomain: 'tickgo-app.firebaseapp.com',
    storageBucket: 'tickgo-app.firebasestorage.app',
    measurementId: 'G-DKHJ6KS0S3',
  );
}
